### ISSUE TITLE
Confusion matrix error: Error: `data` and `reference` should be factors with the same levels.

### ISSUE THREAD

**Issue by fusaroli** [LudvigOlsen/R-cross_validate#8]
Hej Ludvig,
cvms suddenly stopped working on the following script, with the following data. It worked last time I run it in november and now it gives a confusion matrix error. Any quick fix?

[DataLaughLudvig.txt](https://github.com/LudvigOlsen/cvms/files/1959179/DataLaughLudvig.txt)

`Data <- read_delim("DataLaughLudvig.txt",delim="\t")

Data$Truth=as.factor(Data$Truth)

Data <- fold(Data, k = 5) %>% 
  arrange(.folds)

models <- c("Truth ~ 1",
            "Truth ~ 1+MeanInterVoicingInterval",
            "Truth ~ 1+MeanInterVoicingInterval+HNRIQR",
            "Truth ~ 1+MeanInterVoicingInterval+HNRIQR+HNRMedian",
            "Truth ~ 1+MeanInterVoicingInterval+HNRIQR+HNRMedian+PitchLogMedian",
            "Truth ~ 1+MeanInterVoicingInterval+HNRIQR+PitchLogMedian"
)

CV2 <- cross_validate(Data, models, 
                      folds_col = '.folds', 
                      family='binomial')

`

**Comment by LudvigOlsen** [comment]
Hi Ric,  @fusaroli 
Caret had a change that required my attention. My unit tests run again, so your script likely works as well. Thanks for the notice.

 - L
